import React, { useContext, useEffect, useState } from 'react';
import { AppContext } from '../context/AppContext';
import { api } from '../utils/api';
import IsabellaCloud from '../components/IsabellaCloud';
import { selectedEquipmentState } from '../components/portal-backup-state';
import BackupDirectory from '../components/BackupDirectory';
import BackupPolicy from '../components/BackupPolicy';
import BackupRestore from '../components/BackupRestore';
import EquipmentControls from '../components/EquipmentControls';

const agentUrl = 'http://127.0.0.1:18443';
const stateLabel = device => device.status === 'revoked' ? 'Revocado' : device.lastSeenAt && Date.now() - Date.parse(device.lastSeenAt) < 120000 ? 'Conectado' : 'Sin conexión';

export default function Backups({ client: embeddedClient }) {
  const { db, currentUser } = useContext(AppContext);
  const [clientId, setClientId] = useState(embeddedClient?.id || '');
  const [devices, setDevices] = useState([]); const [runs, setRuns] = useState([]); const [alerts, setAlerts] = useState([]); const [snapshots, setSnapshots] = useState([]); const [code, setCode] = useState(null);
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [selectedDeviceId,setSelectedDeviceId]=useState('');const [policies,setPolicies]=useState([]);
  const clients = embeddedClient ? [embeddedClient] : (db?.clients || []); const selected = clients.find(c => c.id === clientId);
  const selectedDevice=devices.find(d=>d.id===selectedDeviceId);
  const assistant = selectedEquipmentState({device:selectedDevice,runs,alerts,snapshots,policies,connection:error?'error':'connected'});
  useEffect(()=>{setSelectedDeviceId(id=>devices.some(d=>d.id===id)?id:(devices[0]?.id||''));},[devices]);
  const operator=currentUser?.role==='Administrador'||(currentUser?.role!=='Cliente'&&currentUser?.allowedSections?.includes('backups'));
  async function refresh() { try { const result = await api('/api/backups'); const visible=(result.devices || []).filter(d => !clientId || d.clientId === clientId); const ids=new Set(visible.map(d=>d.id)); setDevices(visible); setRuns((result.runs || []).filter(r=>ids.has(r.device_id))); setAlerts((result.alerts || []).filter(r=>ids.has(r.device_id))); setSnapshots((result.snapshots || []).filter(r=>ids.has(r.device_id))); setPolicies(result.policies || []); setError(''); } catch (e) { setError(e.message); } }
  useEffect(() => { refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [clientId]);
  useEffect(() => { if (embeddedClient?.id) setClientId(embeddedClient.id); }, [embeddedClient?.id]);
  async function createCode() { if (!clientId) return; setBusy(true); setError(''); setMessage(''); try { setCode(await api('/api/backups/enrollments', { method: 'POST', body: { clientId } })); setMessage('Código creado. Vence en diez minutos.'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function revoke(deviceId) { if (!window.confirm('¿Revocar este equipo? Dejará de enviar respaldos.')) return; setBusy(true); setError(''); try { await api(`/api/backups/devices/${encodeURIComponent(deviceId)}`, { method: 'DELETE', body: {} }); await refresh(); setMessage('Equipo revocado.'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <div className={embeddedClient ? 'backup-workspace' : 'page-container'}>
    <section className="card isabella-dashboard"><label>Equipo que revisa Isabella<select className="form-select" value={selectedDeviceId} onChange={e=>{setSelectedDeviceId(e.target.value);setMessage('');}}><option value="">Selecciona un equipo</option>{devices.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><IsabellaCloud state={error?'alert':assistant.emotion} message={assistant.message} transferring={assistant.transferring} /><div className="backup-progress-panel"><strong>{assistant.progress!==null?`${Math.round(assistant.progress)}%`:assistant.run?'Esperando información de transferencia':'No hay transferencias en curso'}</strong>{(assistant.run||assistant.progress!==null)&&<progress max="100" value={assistant.progress??undefined} aria-label="Porcentaje de transferencia al servidor" />}{assistant.telemetry?.currentFile&&<small>Archivo: {assistant.telemetry.currentFile}</small>}</div></section>
    {!embeddedClient && <div className="page-heading"><div><span className="eyebrow">CONTINUIDAD OPERATIVA</span><h1>Respaldos con Isabella</h1><p className="muted">Vincula los equipos por dominio y envía copias comprimidas por HTTPS.</p></div><a className="btn btn-secondary" href={agentUrl} target="_blank" rel="noreferrer">Abrir Isabella</a></div>}
    <section className="card"><div className="backup-steps"><span><b>1</b>Seleccionar cliente</span><span><b>2</b>Generar código</span><span><b>3</b>Vincular Isabella</span></div><div className="backup-connect"><label>Cliente<select className="form-select" value={clientId} disabled={!!embeddedClient} onChange={e => { setClientId(e.target.value); setCode(null); }}><option value="">Selecciona un cliente</option>{clients.map(c => <option key={c.id} value={c.id}>{c.commercialName || c.businessName || c.name}</option>)}</select></label><button className="btn btn-primary" disabled={!clientId || busy} onClick={createCode}>{busy ? 'Generando…' : 'Generar código de vinculación'}</button></div>{code && <div className="notice success" style={{ marginTop: 20 }}><strong>Código: <code style={{ fontSize: 24, letterSpacing: 5 }}>{code.code}</code></strong><br />Vence: {new Date(code.expiresAt).toLocaleTimeString('es-VE')} · Escríbelo en Isabella.</div>}<div className="notice" style={{ marginTop: 20 }}>Isabella se comunica con <strong>www.jcevnzl.space</strong> por HTTPS. No necesitas IP fija, Radmin VPN ni puertos abiertos. El botón funciona en el mismo equipo donde instalaste el agente.</div>{error && <div className="notice error" role="alert" style={{ marginTop: 20 }}>{error}</div>}{message && <div className="notice success" role="status" style={{ marginTop: 20 }}>{message}</div>}</section>
    <section className="card flush"><div className="section-heading"><div><h2>Equipos vinculados</h2><p className="muted">{selected ? `Cliente: ${selected.commercialName || selected.name}` : 'Selecciona un cliente para ver sus equipos.'}</p></div><span className="status-pill">{devices.length} equipos</span></div><div className="table-scroll"><table className="enterprise-table"><thead><tr><th>Equipo</th><th>Estado</th><th>Última conexión</th><th>Acción</th></tr></thead><tbody>{devices.map(device => <tr key={device.id} className={selectedDeviceId===device.id?'backup-selected-row':''}><td><button className="text-button" onClick={()=>{setSelectedDeviceId(device.id);setMessage('');}}><strong>{device.label}</strong></button><small>{device.id}</small></td><td><span className={`status-pill ${stateLabel(device) === 'Conectado' ? 'ok' : stateLabel(device) === 'Revocado' ? 'error' : 'warn'}`}>{stateLabel(device)}</span></td><td>{device.lastSeenAt ? new Date(device.lastSeenAt).toLocaleString('es-VE') : 'Nunca'}</td><td>{currentUser?.role === 'Administrador' && device.status !== 'revoked' && <button className="text-button" disabled={busy} onClick={() => revoke(device.id)}>Revocar</button>}</td></tr>)}</tbody></table>{!devices.length && <div className="empty-state"><h3>Aún no hay equipos vinculados</h3><p>Genera un código y escribe ese código en Isabella.</p></div>}</div></section>
    <section className="card flush"><div className="section-heading"><div><h2>Actividad de respaldos</h2><p className="muted">Ejecuciones, copias verificadas y alertas del cliente.</p></div><span className="status-pill">{snapshots.length} copias verificadas</span></div><div className="table-scroll"><table className="enterprise-table"><thead><tr><th>Fecha</th><th>Equipo</th><th>Estado</th><th>Snapshot</th></tr></thead><tbody>{runs.slice(0,20).map(run => <tr key={run.id}><td>{run.created_at ? new Date(run.created_at).toLocaleString('es-VE') : '—'}</td><td>{run.device_id}</td><td><span className={`status-pill ${run.status === 'succeeded' ? 'ok' : run.status === 'failed' ? 'error' : 'running'}`}>{run.status}</span></td><td>{run.snapshot_id || 'Pendiente'}</td></tr>)}</tbody></table>{!runs.length && <div className="empty-state"><h3>Sin ejecuciones todavía</h3><p>Cuando Isabella envíe la primera copia aparecerá aquí.</p></div>}</div>{alerts.length > 0 && <div className="notice error" style={{margin:20}}><strong>Alertas activas</strong>{alerts.map(alert => <div key={alert.id}>{alert.message}</div>)}</div>}</section>
    <EquipmentControls key={selectedDevice?.id||'none'} device={selectedDevice} runs={runs} operator={operator} onSaved={refresh} />
    {operator&&<BackupPolicy devices={devices} onSaved={refresh} />}
    {operator&&<BackupDirectory device={selectedDevice} onSaved={refresh} />}
    {operator&&<BackupRestore snapshots={snapshots} clientId={clientId} />}
  </div>;
}
