import React, { useContext, useEffect, useState } from 'react';
import { AppContext } from '../context/AppContext';
import { api } from '../utils/api';
import { MenuIcon } from '../components/EnterpriseNavigation';
const names = { queued:'En cola', preparing:'Preparando', compressing:'Comprimiendo', transferring:'Transfiriendo', verifying:'Verificando', completed:'Verificado', failed:'Fallido', interrupted:'Interrumpido' };
const terminal = ['completed','failed','interrupted'];
const defaults = { enabled:false, time:'22:00', frequency:'daily', days:[1,2,3,4,5], dayOfMonth:1, backupType:'COMPLETO' };
export default function Backups({ client: embeddedClient }) {
  const { db, currentUser } = useContext(AppContext);
  const [clientId,setClientId] = useState(embeddedClient?.id || '');
  const [ip,setIp] = useState('');
  const [data,setData] = useState({ jobs:[], agents:[], schedules:[] });
  const [error,setError] = useState('');
  const [message,setMessage] = useState('');
  const [busy,setBusy] = useState(false);
  const [connection,setConnection] = useState(null);
  const [setup,setSetup] = useState(false);
  const [source,setSource] = useState('C:\\a2Softway\\Data');
  const [destination,setDestination] = useState('');
  const [services,setServices] = useState('');
  const [retention,setRetention] = useState(5);
  const [type,setType] = useState('COMPLETO');
  const [schedule,setSchedule] = useState(defaults);
  const [expanded,setExpanded] = useState(null);
  const client = embeddedClient || db?.clients.find(c => c.id === clientId);
  const agent = data.agents.find(a => a.clientId === clientId);
  const jobs = data.jobs.filter(j => !clientId || j.clientId === clientId);
  const activeJob = data.jobs.find(j => j.clientId === clientId && !terminal.includes(j.status));
  async function refresh() { const result = await api('/api/backups'); setData({jobs:result.jobs || [], agents:result.agents || [], schedules:result.schedules || []}); return result; }
  useEffect(() => {
    let alive=true;
    const poll = async () => { try { const r = await api('/api/backups'); if(alive) setData({jobs:r.jobs || [],agents:r.agents || [],schedules:r.schedules || []}); } catch(e) { if(alive) setError(e.message); } };
    poll(); const timer=setInterval(poll,3000); return () => {alive=false;clearInterval(timer);};
  },[]);
  useEffect(() => {
    setClientId(embeddedClient?.id || clientId);
    setIp(agent?.ip || client?.infrastructure?.vpn?.ip || client?.vpnIp || '');
    setConnection(null);setError('');setMessage('');setSetup(false);
    setSchedule(data.schedules.find(s => s.clientId === (embeddedClient?.id || clientId)) || defaults);
  },[embeddedClient?.id,clientId,agent?.ip]);
  async function action(fn) { setBusy(true);setError('');setMessage(''); try {await fn();} catch(e) {setError(e.message);} finally{setBusy(false);} }
  const connect = () => action(async () => {setConnection(null);const r=await api('/api/backups/connect',{method:'POST',body:{clientId,ip}});setConnection(r);setMessage(`Conectado a ${r.hostname}. ${r.routes?.length || 0} carpeta(s) configurada(s).`);await refresh();});
  const enroll = e => {e.preventDefault();action(async () => {await api('/api/backups/enroll',{method:'POST',body:{clientId,ip,sourceDirs:source.split('\n').map(s=>s.trim()).filter(Boolean),destinationPath:destination,services:services.split(',').map(s=>s.trim()).filter(Boolean),retentionCopies:retention}});await refresh();setSetup(false);setMessage('Agente preparado. Descarga el paquete, instálalo en el cliente y después verifica su conexión.');});};
  const request = () => action(async () => {await api('/api/backups/request',{method:'POST',body:{clientId,backupType:type}});await refresh();setMessage('Trabajo enviado a la cola. Puedes cerrar esta pantalla; el respaldo continúa en segundo plano.');});
  const saveSchedule = e => {e.preventDefault();action(async()=>{await api('/api/backups/schedule',{method:'POST',body:{...schedule,clientId}});await refresh();setMessage('Programación guardada. Se ejecutará con el portal encendido, en la zona horaria America/Caracas.');});};
  return <div className={embeddedClient ? 'backup-workspace' : 'page-container'}>
    {!embeddedClient && <div className="page-heading"><div><span className="eyebrow">CONTINUIDAD OPERATIVA</span><h1>Centro de respaldos</h1><p className="muted">Conexión por IP, ejecución remota y verificación de cada copia.</p></div><span className="status-pill">JC Backup Agent</span></div>}
    <section className="card"><div className="backup-steps"><span><b>1</b>Seleccionar cliente</span><span><b>2</b>Conectar por IP</span><span><b>3</b>Generar y verificar</span></div><div className="backup-connect"><label>Cliente<select className="form-select" value={clientId} disabled={!!embeddedClient} onChange={e=>setClientId(e.target.value)}><option value="">Selecciona un cliente</option>{(db?.clients || []).map(c=><option key={c.id} value={c.id}>{c.commercialName || c.businessName}</option>)}</select></label><label>IP del equipo / Radmin VPN<input className="form-input" placeholder="26.0.0.0" value={ip} onChange={e=>{setIp(e.target.value.trim());setConnection(null);}} /></label><button className="btn btn-primary" disabled={!clientId || !ip || busy} onClick={connect}>{busy ? 'Procesando…' : 'Verificar conexión'}</button></div>
    {error && <div className="notice error" role="alert" style={{marginTop:20}}>{error}</div>}{message && <div className="notice success" role="status" style={{marginTop:20}}>{message}</div>}
    {clientId && <div className="backup-toolbar" style={{marginTop:22}}><span className="muted">{agent ? 'Agente preparado para este cliente.' : 'La primera conexión requiere instalar el agente en el equipo cliente.'}</span>{currentUser.role==='Administrador' && (agent ? <a className="btn btn-secondary" href={`/api/backups/package/${encodeURIComponent(clientId)}`}>Descargar instalador</a> : <button className="btn btn-secondary" onClick={()=>setSetup(!setup)}>{setup ? 'Cerrar configuración' : 'Preparar agente'}</button>)}</div>}
    {setup && <form className="backup-setup" onSubmit={enroll}><label>Carpetas de origen (una por línea)<textarea className="form-textarea" value={source} onChange={e=>setSource(e.target.value)} required /></label><label>Carpeta destino / recurso compartido<input className="form-input" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="\\\\servidor\\Respaldos\\Cliente" required/><small className="muted">Debe ser accesible desde la cuenta que ejecuta el agente.</small></label><label>Servicios de base de datos (opcional)<input className="form-input" value={services} onChange={e=>setServices(e.target.value)} placeholder="FirebirdServerDefaultInstance"/><small className="muted">Nombres separados por comas. Se detienen durante la copia local.</small></label><label>Cadenas completas a conservar<input className="form-input" type="number" min="1" max="100" value={retention} onChange={e=>setRetention(Number(e.target.value))}/></label><div className="wide notice">Instalación única: descarga el paquete, extráelo en el cliente y ejecuta Instalar-Agente.ps1. Después podrás operar ingresando su IP.</div><button className="btn btn-primary" disabled={busy || !ip}>Preparar paquete del cliente</button></form>}
    {connection && <div style={{marginTop:22}}><div className="notice">Equipo: <strong>{connection.hostname}</strong>{connection.routes?.map((r,i)=><div key={i}>{r.source} → {r.destination}</div>)}</div><div className="backup-toolbar" style={{marginTop:16}}><label>Tipo de copia <select className="form-select" value={type} onChange={e=>setType(e.target.value)}><option>COMPLETO</option><option>INCREMENTAL</option><option>DIFERENCIAL</option></select></label><button className="btn btn-primary" disabled={busy || !!activeJob} onClick={request}>{activeJob ? 'Hay un respaldo en curso' : 'Generar respaldo'}</button></div></div>}
    </section>
    <section className="card flush" style={{marginTop:embeddedClient?20:0}}><div className="section-heading"><div><h2>Historial de ejecuciones</h2><p className="muted">Solo se marca como verificada una copia cuya integridad fue comprobada.</p></div><span className="status-pill">{jobs.length} trabajos</span></div><div className="table-scroll"><table className="enterprise-table"><thead><tr><th>Cliente / fecha</th><th>Tipo</th><th>Estado</th><th>Resultado</th><th>Detalle</th></tr></thead><tbody>{jobs.map(job=><React.Fragment key={job.id}><tr><td>{job.clientName}<small>{new Date(job.createdAt).toLocaleString('es-VE')}</small></td><td>{job.backupType}</td><td><span className={`status-pill ${job.status==='completed'?'ok':job.status==='failed'||job.status==='interrupted'?'error':'running'}`}>{names[job.status] || job.status}</span>{!terminal.includes(job.status) && <><div className="job-progress"><span style={{width:`${Math.max(0,Math.min(100,job.progress||0))}%`}}/></div><small>{job.progress || 0}%</small></>}</td><td>{job.connectionError || job.message}<small>{job.total_mb != null ? `${job.total_mb} MB` : ''}</small></td><td><button className="text-button" onClick={()=>setExpanded(expanded===job.id?null:job.id)}>{expanded===job.id?'Cerrar':'Ver detalle'}</button></td></tr>{expanded===job.id && <tr><td colSpan="5"><div className="artifact-list">Trabajo: {job.id}<p>Solicitado por: {job.requestedBy}</p>{(job.artifacts || []).map(a=><div key={a.name}><strong>{a.name}</strong><p>{a.path}</p><code>SHA-256: {a.sha256}</code></div>)}{job.error && <p>{job.error}</p>}<p className="muted">Para restaurar, utiliza restore_backup.py sobre el archivo y una carpeta vacía.</p></div></td></tr>}</React.Fragment>)}</tbody></table>{!jobs.length && <div className="empty-state"><MenuIcon name="database"/><h3>Aún no hay ejecuciones</h3><p>Selecciona un cliente y verifica la conexión con su agente para generar el primer respaldo.</p></div>}</div></section>
    {agent && <section className="card" style={{marginTop:embeddedClient?20:0}}><h2 style={{fontSize:16}}>Programación automática</h2><form className="backup-setup" onSubmit={saveSchedule}><label>Estado<select className="form-select" value={String(schedule.enabled)} onChange={e=>setSchedule({...schedule,enabled:e.target.value==='true'})}><option value="false">Desactivada</option><option value="true">Activada</option></select></label><label>Frecuencia<select className="form-select" value={schedule.frequency} onChange={e=>setSchedule({...schedule,frequency:e.target.value})}><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="monthly">Mensual</option></select></label><label>Hora (Venezuela)<input type="time" className="form-input" required value={schedule.time} onChange={e=>setSchedule({...schedule,time:e.target.value})}/></label><label>Tipo<select className="form-select" value={schedule.backupType} onChange={e=>setSchedule({...schedule,backupType:e.target.value})}><option>COMPLETO</option><option>INCREMENTAL</option><option>DIFERENCIAL</option></select></label>{schedule.frequency==='weekly' && <div className="wide" style={{display:'flex',gap:15,flexWrap:'wrap'}}>{['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'].map((day,i)=><label key={day}><input type="checkbox" checked={schedule.days.includes(i)} onChange={e=>setSchedule({...schedule,days:e.target.checked?[...schedule.days,i]:schedule.days.filter(d=>d!==i)})}/>{day}</label>)}</div>}{schedule.frequency==='monthly' && <label>Día del mes (1–28)<input className="form-input" type="number" min="1" max="28" value={schedule.dayOfMonth} onChange={e=>setSchedule({...schedule,dayOfMonth:Number(e.target.value)})}/></label>}<div className="wide muted">El portal debe permanecer encendido. Los trabajos pendientes se reanudan al recuperar la conexión.</div><button className="btn btn-primary" disabled={busy}>Guardar programación</button></form></section>}
  </div>;
}
