import React, { useEffect, useState } from 'react';
import { api } from '../utils/api';
const defaults={sourceDirs:[],excludes:[],days:[1,2,3,4,5],time:'22:00',timezone:'America/Caracas',compression:'auto',retentionSuccessfulCount:7,consistencyProfile:'files',enabled:false};
export default function BackupPolicy({devices,onSaved}) {
 const [deviceId,setDeviceId]=useState(''),[policy,setPolicy]=useState(defaults),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');
 useEffect(()=>{if(!devices.some(d=>d.id===deviceId))setDeviceId('');},[devices,deviceId]);
 useEffect(()=>{if(!deviceId)return;let active=true;setBusy(true);setError('');setSaved('');api(`/api/backups/devices/${encodeURIComponent(deviceId)}/policy`).then(data=>{if(active)setPolicy({...defaults,...data.policy});}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[deviceId]);
 const change=(name,value)=>setPolicy(p=>({...p,[name]:value}));
 async function save(event){event.preventDefault();setBusy(true);setError('');try{await api('/api/backups/policies',{method:'POST',body:{deviceId,...policy,sourceDirs:policy.sourceDirs.filter(Boolean),excludes:policy.excludes.filter(Boolean)}});setSaved('Configuración guardada. Isabella la recibe en su próxima conexión.');onSaved?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function runNow(){setBusy(true);setError('');try{await api('/api/backups/runs',{method:'POST',body:{deviceId}});setSaved('Respaldo en cola. Isabella lo ejecutará al conectarse.');onSaved?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="card"><h2>Programación por equipo</h2><p className="muted">Isabella ejecutará las tareas en segundo plano y enviará las copias al servidor por HTTPS.</p><label>Equipo<select className="form-select" value={deviceId} onChange={e=>setDeviceId(e.target.value)}><option value="">Selecciona un equipo vinculado</option>{devices.filter(d=>d.status==='active').map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label>{deviceId&&<form onSubmit={save} className="isabella-config" style={{marginTop:20}}><label className="wide">Carpetas absolutas, una por línea<textarea value={policy.sourceDirs.join('\n')} onChange={e=>change('sourceDirs',e.target.value.split('\n'))} required placeholder={'C:\\Datos\nD:\\Clientes'} /></label><label className="wide">Exclusiones, una por línea<textarea value={policy.excludes.join('\n')} onChange={e=>change('excludes',e.target.value.split('\n'))} /></label><fieldset className="wide"><legend>Días</legend>{['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'].map((day,index)=><label key={day} style={{display:'inline-flex',flexDirection:'row',marginRight:14}}><input type="checkbox" checked={policy.days.includes(index)} onChange={e=>change('days',e.target.checked?[...policy.days,index]:policy.days.filter(d=>d!==index))} />{day}</label>)}</fieldset><label>Hora<input type="time" value={policy.time} required onChange={e=>change('time',e.target.value)} /></label><label>Zona horaria<input value={policy.timezone} required onChange={e=>change('timezone',e.target.value)} /></label><label>Compresión<select value={policy.compression} onChange={e=>change('compression',e.target.value)}><option value="auto">Automática</option><option value="max">Máxima</option></select></label><label>Copias verificadas que conservar<input type="number" min="1" max="365" value={policy.retentionSuccessfulCount} onChange={e=>change('retentionSuccessfulCount',Number(e.target.value))} /></label><label>Consistencia<select value={policy.consistencyProfile} onChange={e=>change('consistencyProfile',e.target.value)}><option value="files">Archivos</option><option value="files-vss">Instantánea Windows VSS</option></select></label><label className="wide" style={{flexDirection:'row'}}><input type="checkbox" checked={policy.enabled} onChange={e=>change('enabled',e.target.checked)} />Activar respaldos programados</label><div className="wide"><button className="btn btn-primary" disabled={busy}>{busy?'Guardando…':'Guardar programación'}</button> <button type="button" className="btn btn-secondary" disabled={busy} onClick={runNow}>Respaldar ahora</button></div></form>}{error&&<p role="alert" className="notice error">{error}</p>}{saved&&<p role="status" className="notice success">{saved}</p>}</section>;
}


