import React, { useContext, useEffect, useRef, useState } from 'react';
import { AppContext } from '../context/AppContext';
const titles={dashboard:'Resumen',clients:'Clientes',projects:'Proyectos',agenda:'Agenda',tickets:'Centro de soporte',backups:'Respaldos',jc:'Conocimiento y recursos',layouts:'Infraestructura',employees:'Equipo',analytics:'Reportes',audit:'Auditoría',users:'Usuarios y permisos'};
export default function Header(){
 const {activeTab,currentUser,theme,setTheme,notifications,clearNotifications}=useContext(AppContext);
 const [open,setOpen]=useState(false);const panel=useRef(null);
 const unread=notifications.filter(n=>!n.read).length;
 useEffect(()=>{const close=e=>{if(!panel.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 return <header className="header-bar enterprise-header"><div className="header-breadcrumb"><span>Operaciones</span><span aria-hidden="true">/</span><strong>{titles[activeTab]||'JC Enterprise'}</strong></div><div className="header-actions"><button className="header-icon" title="Cambiar tema" aria-label="Cambiar tema" onClick={()=>setTheme(theme==='light'?'dark':'light')}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M21 13A9 9 0 0 1 11 3 9 9 0 1 0 21 13Z"/></svg></button><div ref={panel} style={{position:'relative'}}><button className="header-icon" aria-expanded={open} aria-label={`Notificaciones: ${unread} sin leer`} onClick={()=>setOpen(!open)}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>{unread>0&&<span className="notification-count">{unread>99?'99+':unread}</span>}</button>{open&&<section className="notification-panel"><div className="section-heading"><h2>Notificaciones</h2><button className="text-button" onClick={clearNotifications}>Marcar leídas</button></div>{notifications.length?notifications.slice(0,20).map(n=><div className={`notification-row ${n.read?'':'unread'}`} key={n.id}><p>{n.text}</p><small>{new Date(n.time).toLocaleString('es-VE')}</small></div>):<p className="muted">No hay notificaciones pendientes.</p>}</section>}</div><span className="header-divider"/><div className="header-user"><strong>{currentUser?.name}</strong><small>{currentUser?.role}</small></div></div></header>;
}
