import React,{useEffect,useRef,useState} from 'react';
import {api} from '../utils/api';
export default function EquipmentControls({device,runs=[],operator,onSaved}){
 const [editing,setEditing]=useState(false),[label,setLabel]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[chatBusy,setChatBusy]=useState(false);const active=useRef(device?.id);
 useEffect(()=>{active.current=device?.id;setEditing(false);setLabel(device?.label||'');setNotes(device?.notes||'');setMessages([]);setNotice('');setQuestion('');setChatBusy(false);},[device?.id]);
 if(!device)return null;
 const jobs=runs.filter(r=>r.device_id===device.id&&['queued','running','retry_wait'].includes(r.status));
 async function edit(e){e.preventDefault();setBusy(true);try{await api(`/api/backups/devices/${device.id}/edit`,{method:'POST',body:{label,notes}});setEditing(false);setNotice('Información guardada.');await onSaved();}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 async function stop(run){if(!window.confirm(`¿Detener el respaldo de ${device.label}?`))return;setBusy(true);try{const result=await api(`/api/backups/runs/${run.id}/stop`,{method:'POST',body:{}});setNotice(result.status==='cancelled'?'Tarea pendiente cancelada.':'Detención solicitada. Esperando confirmación del agente.');await onSaved();}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 async function talk(e){e.preventDefault();const text=question.trim(),id=device.id;if(!text||chatBusy)return;setQuestion('');setMessages(m=>[...m,{role:'Tú',text}].slice(-20));setChatBusy(true);try{const result=await api(`/api/backups/devices/${id}/chat`,{method:'POST',body:{message:text}});if(active.current===id)setMessages(m=>[...m,{role:'Isabella',text:result.answer}].slice(-20));}catch(e){if(active.current===id)setMessages(m=>[...m,{role:'Isabella',text:e.message}]);}finally{if(active.current===id)setChatBusy(false);}}
 return <section className="card"><h2>Equipo: {device.label}</h2>{device.notes&&<p>{device.notes}</p>}{operator&&<><button className="btn btn-secondary" onClick={()=>setEditing(!editing)} disabled={busy}>Editar equipo</button>{editing&&<form onSubmit={edit}><label>Nombre<input className="form-input" maxLength={120} required value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Notas<textarea className="form-input" maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>Guardar información</button></form>}<p className="muted">Las carpetas y el horario se editan en Configuración de respaldos; el destino se cambia en Directorio de guardado.</p>{jobs.map(run=><div key={run.id} className="isabella-actions"><span>{run.status==='running'?'Respaldo en ejecución':'Respaldo pendiente'}</span><button className="btn btn-secondary" disabled={busy||run.cancel_requested||(run.status==='running'&&!device.supportsCancel)} onClick={()=>stop(run)}>{run.cancel_requested?'Detención solicitada':run.status==='running'&&!device.supportsCancel?'Actualizar motor para detener':'Detener respaldo'}</button></div>)}</>}{notice&&<p role="status">{notice}</p>}<h3>Conversar con Isabella</h3><p className="muted">Asistente de diagnóstico basado en el estado del equipo. Puedes preguntarle «¿Por qué no funciona?» o «¿Dónde se guarda?». Las órdenes se realizan con los botones.</p><div className="isabella-chat" role="log" aria-live="polite" aria-label="Conversación con Isabella">{messages.map((m,i)=><p key={i}><strong>{m.role}: </strong>{m.text}</p>)}</div><form onSubmit={talk}><label>Tu pregunta<input className="form-input" value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} required /></label><button className="btn btn-primary" disabled={chatBusy}>{chatBusy?'Consultando equipo…':'Hablar con Isabella'}</button></form></section>;
}
