import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8').replaceAll('\r\n','\n');
const write=(p,s)=>fs.writeFileSync(new URL('../'+p,import.meta.url),s);
let s=read('src/views/Clients.jsx');
s=s.replace("import Layouts from './Layouts';","import Layouts from './Layouts';\nimport Backups from './Backups';");
const start=s.indexOf('function ClockProgressBar(');
if(start<0)throw new Error('Backup component marker missing');
s=s.slice(0,start)+`function ClientBackupsManager({ activeClient }) {\n  return <Backups key={activeClient.id} client={activeClient} />;\n}\n`;
write('src/views/Clients.jsx',s);
s=read('src/views/JcView.jsx');
s=s.replace("import ServiceReports from './ServiceReports';","import ServiceReports from './ServiceReports';\nimport Backups from './Backups';");
const a=s.indexOf('function BackupsCenterView()'),b=s.indexOf('function ServersDirectoryView()',a);
if(a<0||b<0)throw new Error('Jc view marker missing');
s=s.slice(0,a)+'function BackupsCenterView() { return <Backups />; }\n\n'+s.slice(b);
write('src/views/JcView.jsx',s);
s=read('src/utils/crypto.js');
const enc=s.indexOf('export async function encryptData('),dec=s.indexOf('export async function decryptData(');
s="import { api } from './api';\n"+s.slice(0,enc)+`export async function encryptData(text) {\n  if(!text)return '';\n  const result=await api('/api/vault/encrypt',{method:'POST',body:{text}});return result.value;\n}\n\n`+s.slice(dec);
s=s.replace("    if (payload.mode === 'fallback'", "    if (payload.mode === 'server-v1') { const result=await api('/api/vault/decrypt',{method:'POST',body:{value:encryptedJsonString}});return result.value; }\n    if (payload.mode === 'fallback'");
write('src/utils/crypto.js',s);
